import { z } from "zod";
import { defineEndpoint } from "../api.js";
import { listMetaSchema } from "../list.js";
import {
  createHouseholdBodySchema,
  createHouseholdInviteBodySchema,
  householdIdParamsSchema,
  inviteIdParamsSchema,
  inviteParamsSchema,
  inviteTokenBodySchema,
  listHouseholdInvitesQuerySchema,
  listHouseholdMembersQuerySchema,
  listHouseholdsQuerySchema,
  listMyHouseholdInvitesQuerySchema,
  memberParamsSchema,
  previewInviteQuerySchema,
  updateHouseholdBodySchema,
  updateHouseholdMemberBodySchema,
} from "./requests.js";
import {
  acceptHouseholdInviteSchema,
  householdInviteLinkSchema,
  householdInviteSchema,
  householdInviteStatusMetadataSchema,
  householdMemberSchema,
  householdPermissionMetadataSchema,
  householdRoleMetadataSchema,
  householdSchema,
  previewHouseholdInviteSchema,
} from "./resource.js";

export const householdsEndpoints = {
  list: defineEndpoint({
    method: "get",
    path: "/households",
    query: listHouseholdsQuerySchema,
    response: z.array(householdSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  create: defineEndpoint({
    method: "post",
    path: "/households",
    body: createHouseholdBodySchema,
    response: householdSchema,
    status: 201,
  }),
  roles: defineEndpoint({
    method: "get",
    path: "/households/roles",
    response: z.array(householdRoleMetadataSchema),
    status: 200,
  }),
  permissions: defineEndpoint({
    method: "get",
    path: "/households/permissions",
    response: z.array(householdPermissionMetadataSchema),
    status: 200,
  }),
  inviteStatuses: defineEndpoint({
    method: "get",
    path: "/households/invite-statuses",
    response: z.array(householdInviteStatusMetadataSchema),
    status: 200,
  }),
  previewInvite: defineEndpoint({
    method: "get",
    path: "/households/invites/preview",
    query: previewInviteQuerySchema,
    response: previewHouseholdInviteSchema,
    status: 200,
  }),
  myInvites: defineEndpoint({
    method: "get",
    path: "/households/invites",
    query: listMyHouseholdInvitesQuerySchema,
    response: z.array(householdInviteSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  acceptInvite: defineEndpoint({
    method: "post",
    path: "/households/invites/accept",
    body: inviteTokenBodySchema,
    response: acceptHouseholdInviteSchema,
    status: 200,
  }),
  rejectInvite: defineEndpoint({
    method: "post",
    path: "/households/invites/reject",
    body: inviteTokenBodySchema,
    status: 204,
  }),
  acceptInviteById: defineEndpoint({
    method: "post",
    path: "/households/invites/:inviteId/accept",
    params: inviteIdParamsSchema,
    response: acceptHouseholdInviteSchema,
    status: 200,
  }),
  rejectInviteById: defineEndpoint({
    method: "post",
    path: "/households/invites/:inviteId/reject",
    params: inviteIdParamsSchema,
    status: 204,
  }),
  get: defineEndpoint({
    method: "get",
    path: "/households/:id",
    params: householdIdParamsSchema,
    response: householdSchema,
    status: 200,
  }),
  update: defineEndpoint({
    method: "patch",
    path: "/households/:id",
    params: householdIdParamsSchema,
    body: updateHouseholdBodySchema,
    response: householdSchema,
    status: 200,
  }),
  delete: defineEndpoint({
    method: "delete",
    path: "/households/:id",
    params: householdIdParamsSchema,
    status: 204,
  }),
  members: defineEndpoint({
    method: "get",
    path: "/households/:id/members",
    params: householdIdParamsSchema,
    query: listHouseholdMembersQuerySchema,
    response: z.array(householdMemberSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  updateMember: defineEndpoint({
    method: "patch",
    path: "/households/:id/members/:userId",
    params: memberParamsSchema,
    body: updateHouseholdMemberBodySchema,
    response: householdMemberSchema,
    status: 200,
  }),
  removeMember: defineEndpoint({
    method: "delete",
    path: "/households/:id/members/:userId",
    params: memberParamsSchema,
    status: 204,
  }),
  invites: defineEndpoint({
    method: "get",
    path: "/households/:id/invites",
    params: householdIdParamsSchema,
    query: listHouseholdInvitesQuerySchema,
    response: z.array(householdInviteSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  createInvite: defineEndpoint({
    method: "post",
    path: "/households/:id/invites",
    params: householdIdParamsSchema,
    body: createHouseholdInviteBodySchema,
    response: householdInviteSchema,
    status: 201,
  }),
  refreshInviteLink: defineEndpoint({
    method: "post",
    path: "/households/:id/invites/:inviteId/link",
    params: inviteParamsSchema,
    response: householdInviteLinkSchema,
    status: 200,
  }),
  resendInvite: defineEndpoint({
    method: "post",
    path: "/households/:id/invites/:inviteId/resend",
    params: inviteParamsSchema,
    status: 204,
  }),
  cancelInvite: defineEndpoint({
    method: "delete",
    path: "/households/:id/invites/:inviteId",
    params: inviteParamsSchema,
    status: 204,
  }),
} as const;
