import { z } from "zod";
import { defineEndpoint } from "../api.js";
import { listMetaSchema } from "../list.js";
import {
  createCreditCardInputSchema,
  createCreditCardPaymentInputSchema,
  createCreditCardPurchaseInputSchema,
  creditCardCycleParamsSchema,
  creditCardForecastQuerySchema,
  creditCardIdParamsSchema,
  creditCardPaymentParamsSchema,
  creditCardPurchaseParamsSchema,
  listCreditCardCyclesQuerySchema,
  listCreditCardsQuerySchema,
  updateCreditCardCycleInputSchema,
  updateCreditCardInputSchema,
  updateCreditCardPaymentInputSchema,
  updateCreditCardPurchaseInputSchema,
} from "./requests.js";
import {
  creditCardCycleDetailsSchema,
  creditCardCycleSchema,
  creditCardForecastSchema,
  creditCardPaymentSchema,
  creditCardPurchaseSchema,
  creditCardSchema,
} from "./resource.js";

export const creditCardsEndpoints = {
  list: defineEndpoint({
    method: "get",
    path: "/credit-cards",
    query: listCreditCardsQuerySchema,
    response: z.array(creditCardSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  create: defineEndpoint({
    method: "post",
    path: "/credit-cards",
    body: createCreditCardInputSchema,
    response: creditCardSchema,
    status: 201,
  }),
  get: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id",
    params: creditCardIdParamsSchema,
    response: creditCardSchema,
    status: 200,
  }),
  update: defineEndpoint({
    method: "patch",
    path: "/credit-cards/:id",
    params: creditCardIdParamsSchema,
    body: updateCreditCardInputSchema,
    response: creditCardSchema,
    status: 200,
  }),
  delete: defineEndpoint({
    method: "delete",
    path: "/credit-cards/:id",
    params: creditCardIdParamsSchema,
    status: 204,
  }),
  cycles: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id/cycles",
    params: creditCardIdParamsSchema,
    query: listCreditCardCyclesQuerySchema,
    response: z.array(creditCardCycleSchema),
    meta: listMetaSchema(),
    status: 200,
  }),
  getCycle: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id/cycles/:cycleId",
    params: creditCardCycleParamsSchema,
    response: creditCardCycleDetailsSchema,
    status: 200,
  }),
  updateCycle: defineEndpoint({
    method: "patch",
    path: "/credit-cards/:id/cycles/:cycleId",
    params: creditCardCycleParamsSchema,
    body: updateCreditCardCycleInputSchema,
    response: creditCardCycleDetailsSchema,
    status: 200,
  }),
  createPurchase: defineEndpoint({
    method: "post",
    path: "/credit-cards/:id/purchases",
    params: creditCardIdParamsSchema,
    body: createCreditCardPurchaseInputSchema,
    response: creditCardPurchaseSchema,
    status: 201,
  }),
  getPurchase: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id/purchases/:purchaseId",
    params: creditCardPurchaseParamsSchema,
    response: creditCardPurchaseSchema,
    status: 200,
  }),
  updatePurchase: defineEndpoint({
    method: "patch",
    path: "/credit-cards/:id/purchases/:purchaseId",
    params: creditCardPurchaseParamsSchema,
    body: updateCreditCardPurchaseInputSchema,
    response: creditCardPurchaseSchema,
    status: 200,
  }),
  deletePurchase: defineEndpoint({
    method: "delete",
    path: "/credit-cards/:id/purchases/:purchaseId",
    params: creditCardPurchaseParamsSchema,
    status: 204,
  }),
  createPayment: defineEndpoint({
    method: "post",
    path: "/credit-cards/:id/payments",
    params: creditCardIdParamsSchema,
    body: createCreditCardPaymentInputSchema,
    response: creditCardPaymentSchema,
    status: 201,
  }),
  getPayment: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id/payments/:paymentId",
    params: creditCardPaymentParamsSchema,
    response: creditCardPaymentSchema,
    status: 200,
  }),
  updatePayment: defineEndpoint({
    method: "patch",
    path: "/credit-cards/:id/payments/:paymentId",
    params: creditCardPaymentParamsSchema,
    body: updateCreditCardPaymentInputSchema,
    response: creditCardPaymentSchema,
    status: 200,
  }),
  deletePayment: defineEndpoint({
    method: "delete",
    path: "/credit-cards/:id/payments/:paymentId",
    params: creditCardPaymentParamsSchema,
    status: 204,
  }),
  forecast: defineEndpoint({
    method: "get",
    path: "/credit-cards/:id/forecast",
    params: creditCardIdParamsSchema,
    query: creditCardForecastQuerySchema,
    response: creditCardForecastSchema,
    status: 200,
  }),
} as const;
